### ISSUE TITLE
Is it possible to use your plugin in Ionic project (capacitor)?

### ISSUE THREAD

**Issue by tgprudencio** [Zeno97/cordova-plugin-jitsi-meet-sdk#23]
Hi, how are you? I have an Ionic project (capacitor 3) and I've been searching for a plugin which has all the listeners available and also commands (for example, the getParticipantsInfo) and I ended up here... So, do you know if it's possible do import to my project and how I could do it? Or would it be better to create another ionic project using cordova (I don't know if changes anything)...
Thank you in advance,
Thiago.

**Comment by Zeno97** [comment]
Hello.
Capacitor is a different framework from Cordova and then is not possible to use cordova plugins like this one.
About creating another ionic project with cordova is up to you but keep in mind you could meet some difficult because plugins are different.

As an alternative if you can handle a bit of native android/ios development you could with a little effort fork and convert this plugin into one with capacitor compatibility.



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Thiago Gonçalves Prudêncio ***@***.***>
Data: 10/08/22 19:11 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Zeno97/cordova-plugin-jitsi-meet-sdk] Is it possible to use your plugin in Ionic project (capacitor)? (Issue #23)


Hi, how are you? I have a ionic project (capacitor 3) and I've been searching for a plugin which has all the listeners available and also commands (for example, the getParticipantsInfo) and I ended up here... So, do you know if it's possible do import to my project and how I could do it? Or would it be better to create another ionic project using cordova (I don't know if changes anything)...
Thank you in advance,
Thiago.

**Comment by tgprudencio** [comment]
Hi, thank you for the repsonse...
So the best option would be importing your plugin in native project app? Or would it work if I use something else? like React Native? 
I'm trying to find the best approach to test and use your plugin because I've never created/changed any plugin to import in my projects, so I don't know where I could start from...
Thank you once again

**Comment by tgprudencio** [comment]
Hello @Zeno97, how are you?
I created an Ionic project using cordova this time to test your plugin, but I still didn't succeeded it... I could install it and I see the folders created by it, which seems quite fine, but I still can't import it to my project... is there any step I'm missing? I'm really looking forward to make it work
Thank you in advance

**Comment by Zeno97** [comment]
No. What i was suggesting is to CREATE A PLUGIN for Capacitor using this one as a basis.

Cordova plugin has a javascript file with the methods you call inside (startCall, disposeCall,) and also .java and .h/.m files where native implementation is.

Basically when you use a javascript method for a plugin everything starts from JitsiMeet.java when you are in android and CDVJitsimeet.m in ios (look at src folder).

Almost the same is for capacitor. Look at the documentation about Cordova plugin development and Capacitor plugin development. You will see it.



Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Thiago Gonçalves Prudêncio ***@***.***>
Data: 10/08/22 19:35 (GMT+01:00)
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Massimiliano Coppola ***@***.***>, Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] Is it possible to use your plugin in Ionic project (capacitor)? (Issue #23)


Hi, thank you for the repsonse...
So the best option would be importing your plugin in native project app? Or would it work if I use something else? like React Native?
I'm trying to find the best approach to test and use your plugin because I've never created/changed any plugin to import in my projects, so I don't know where I could start from...
Thank you once again

**Comment by tgprudencio** [comment]
Oh, I see, thank you for the reply. I'll work on that.
