### ISSUE TITLE
cant use it

### ISSUE THREAD

**Issue by ebsigma** [Zeno97/cordova-plugin-jitsi-meet-sdk#6]
This is the plugin I am trying to use: https://www.npmjs.com/package/cordova-plugin-jitsi-meet
I install it "cordova plugin add cordova-plugin-jitsi-meet"
and the errors are in order the minimum version of the sdk that is in 22 and asks for 23 (the change in android studio since otherwise the change is not saved)
then the error is that the gradle you have is 6.
5 and it needs 6.7.1, so I get into platforms / android / cordova / lib / builders / and change in projectbuilder.js the variable where the gradle is so that it has the 6.7.1, and the last error it gives me after that is:

What went wrong:
Execution failed for task ': app: processDebugResources'.
> A failure occurred while executing com.android.build.gradle.
internal.res.LinkApplicationAndroidResourcesTask $ TaskAction
   > Android resource linking failed
     ERROR: C: \ Users \ ebsig \ Dropbox \ Work \ cordova vcall \ Vcall - copy \ platforms \ android \ app \ build \ intermediates \ packaged_manifests \ debug \ AndroidManifest.xml: 68: AAPT: error: resource style / Theme.Design .NoActionBar (aka com.iapps.vcall: style / Theme.Design
.NoActionBar) not found.

with the same error 6.9.
And from there it does not happen, since if I put the last gradle that exists (7.0.2) it gives me another different failure:

Where:
Build file 'C: \ Users \ ebsig \ Dropbox \ Work \ cordova vcall \ Vcall - copy \ platforms \ android \ CordovaLib \ build.gradle' line: 50

* What went wrong:
A problem occurred evaluating project ': CordovaLib'.
> Failed to apply plugin 'com.github.dcendents.android-maven'.
   > Could not create plugin of type 'AndroidMavenPlugin'.
      > Could not generate a decorated class for type AndroidMavenPlugin.
         > org / gradle / api / publication / maven / internal / MavenPomMetaInfoProvider

so I don't know what else to do

**Comment by Zeno97** [comment]
Hello thanks for trying to use my plugin in your case.
Each plugin may have gradle files and each one may require a minimum version of the SDK.
Then you can imagine that this can cause conflitcs.

I suggest you to setup minimum sdk version from config.xml and then remove and add platform

This is not caused by the plugin. You can create an app from scratch and install only my plugin and run it. It will work.
Let me know anyway
________________________________
Da: ebsigma ***@***.***>
Inviato: mercoledì 9 giugno 2021 12:26
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Zeno97/cordova-plugin-jitsi-meet-sdk] cant use it (#6)


This is the plugin I am trying to use: https://www.npmjs.com/package/cordova-plugin-jitsi-meet
I install it "cordova plugin add cordova-plugin-jitsi-meet"
and the errors are in order the minimum version of the sdk that is in 22 and asks for 23 (the change in android studio since otherwise the change is not saved)
then the error is that the gradle you have is 6.
5 and it needs 6.7.1, so I get into platforms / android / cordova / lib / builders / and change in projectbuilder.js the variable where the gradle is so that it has the 6.7.1, and the last error it gives me after that is:

What went wrong:
Execution failed for task ': app: processDebugResources'.

A failure occurred while executing com.android.build.gradle.
internal.res.LinkApplicationAndroidResourcesTask $ TaskAction
Android resource linking failed
ERROR: C: \ Users \ ebsig \ Dropbox \ Work \ cordova vcall \ Vcall - copy \ platforms \ android \ app \ build \ intermediates \ packaged_manifests \ debug \ AndroidManifest.xml: 68: AAPT: error: resource style / Theme.Design .NoActionBar (aka com.iapps.vcall: style / Theme.Design
.NoActionBar) not found.

with the same error 6.9.
And from there it does not happen, since if I put the last gradle that exists (7.0.2) it gives me another different failure:

Where:
Build file 'C: \ Users \ ebsig \ Dropbox \ Work \ cordova vcall \ Vcall - copy \ platforms \ android \ CordovaLib \ build.gradle' line: 50

  *   What went wrong:
A problem occurred evaluating project ': CordovaLib'.

Failed to apply plugin 'com.github.dcendents.android-maven'.
Could not create plugin of type 'AndroidMavenPlugin'.
> Could not generate a decorated class for type AndroidMavenPlugin.
> org / gradle / api / publication / maven / internal / MavenPomMetaInfoProvider

so I don't know what else to do

**Comment by ebsigma** [comment]
What version of the gradle and minimum and recommended SDK do you recommend for it, the error is the same with a new project.

**Comment by Zeno97** [comment]
23
________________________________
Da: ebsigma ***@***.***>
Inviato: mercoledì 9 giugno 2021 12:39
A: Zeno97/cordova-plugin-jitsi-meet-sdk ***@***.***>
Cc: Zeno97 ***@***.***>; Comment ***@***.***>
Oggetto: Re: [Zeno97/cordova-plugin-jitsi-meet-sdk] cant use it (#6)


What version of the gradle and minimum and recommended SDK do you recommend for it, the error is the same with a new project.

**Comment by ebsigma** [comment]
I had been with the same error for DAYS and could not find the solution ...

In the end, I created a new project and installed this plugin first, then the android platform and then the rest of the plugins that I needed.

Thanks for your help

**Comment by Zeno97** [comment]
Hi @ebsigma  i've implemented newer jitsi meet sdk, fixed some issue and also implemented participant related listeners.
You can find every new implementation in the doc.
